config/routes.rb
Rails.application.routes.draw do
  resources :restaurants, only: [:index, :new, :create, :show, :edit, :update]  
  resources :restaurant_foods, only: [:index, :create, :new, :show, :edit, :update]
  resources :organizations
  resources :exchanges

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exchange.rb
class Exchange < ApplicationRecord
    belongs_to :restaurant
    belongs_to :organization, optional: true
end

app/models/organization.rb
class Organization < ApplicationRecord
    has_many :exchanges
    has_many :restaurants, through: :exchanges
    has_secure_password

# validates :phone_number, length: {is: 10}
# validates :name, :street_address, :city, :state, :zip_code, :contact_email, :phone_number, presence: true
# validates :zip_code, length: {is: 5}
# validates :contact_email, uniqueness: true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :exchanges
    has_many :organizations, through: :exchanges
    has_many :restaurant_foods
    has_secure_password 

    
end

app/models/restaurant_food.rb
class RestaurantFood < ApplicationRecord
    belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :current_restaurant

    def current_restaurant 
        @current_restaurant = Restaurant.find_by(id: session[:restaurant_id])
    end
end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController

    def index
        @exchanges = Exchange.all
    end

    def new
        @exchange = Exchange.new
    end
    
    def show
        @exchange = Exchange.find(params[:id])
    end

    def create 
        @exchange = Exchange.create(exchange_params)
        session[:restaurant_id] = @current_restaurant.id
        # change_food_status
        redirect_to exchanges_path(@exchange.id)
    end
   
    private 

    def exchange_params
        params.require(:exchange).permit(:restaurant_id, :organziation_id, :exchange_start, :exchange_end, :status, :notes)
    end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

    def index
        @organizations = Organization.all
    end

    def show
        @organization = Organization.find(params[:id])
    end

    def edit
        @organization = Organization.find(params[:id])
    end
    
    def update
        @organization = Organization.find(params[:id])
        @organization.update(organization_params)
        redirect_to organization_path(@organization.id)
    end

    def new
        @organization = Organization.new
    end

    def create
        @organizations = Organization.new(organization_params)
        @organization.save
        session[:organization_id] = @organization.id
        redirect_to organization_path(@organization.id)
    end

    private

    def organization_params
        params.require(:organizations).permit(:name, :street_address, :city, :state, :zip_code, :contact_email, :phone_number)
    end
end

app/controllers/restaurant_foods_controller.rb
class RestaurantFoodsController < ApplicationController
    
    def show
        @restaurant_food = RestaurantFood.find(params[:id])
    end

    def new
        @restaurant_food = RestaurantFood.new
    end

    def edit 
        @restaurant_food = RestaurantFood.find(params[:id])
    end

    def create
        params_hash = rest_food_params
        params_hash[:restaurant_id] = @current_restaurant.id        
        @restaurant_food = RestaurantFood.create(params_hash)
        redirect_to restaurant_path(@current_restaurant.id) 
        # else
        #     flash[:errors].@restaurant_food.error.full_messages
        #     redirect_to new_restaurant_food_path #need this redirect to new page         
        # end
    end

    def update  
        params_hash = rest_food_params
        params_hash[:restaurant_id] = @current_restaurant.id
        @restaurant_food = RestaurantFood.update(params_hash)
        redirect_to restaurant_path(@current_restaurant.id)
    end

    private

    def rest_food_params 
        params.require(:restaurant_food).permit(:restaurant_id, :food_type, :quantity, :use_by, :notes)
    end
    
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    
    def new
        @restaurant = Restaurant.new
    end

    def show 
        @restaurant = Restaurant.find(params[:id])
        
    end

    def edit
        @restaurant = Restaurant.find(params[:id])
    end

    def create 
        @restaurant = Restaurant.create(restaurant_params)
        session[:restaurant_id] = @restaurant.id 
        redirect_to restaurant_path(@restaurant.id)
    end

    def update 
        @restaurant = Restaurant.find(@current_restaurant.id)
        @restaurant.update(restaurant_params)
        redirect_to restaurant_path(@restaurant)
    end

    private 

    def restaurant_params 
        params.require(:restaurant).permit(:name, :street_address, :city, :state, :zip_code, :contact_email, :phone_number, :password_digest)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exchanges_helper.rb
module ExchangesHelper
    # def display_exchange_contents
    #     @current_restaurant.restaurant_foods.each do |food|
    #         # byebug
    #         print food.food_type
    #     end
    # end

    def change_food_status
        @current_restaurant.restaurant_foods.each do |food| 
            if food.status == true
               food.status = false                
            else                
            end
        end
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/restaurant_foods_helper.rb
module RestaurantFoodsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/exchanges/index.html.erb
<h1> Welcome to your Sustainab.ly Exchange, <%= @current_restaurant.name%>!</h1>

<h4> On the Sustainab.ly Marketplace, restaurants in our network offer </h4>
<h4> up their excess foods and organizations can claim for distribution! </h4>
<h4> It's a win-win! We LOVE win-wins!! </h4>

<u><h4> Below are all your pending exchanges: </h4></u>

<% Exchange.all.each do |exchange| %>
<div style="height:px;width:500px;border:1px solid #ccc;font:16px/26px Georgia, Garamond, Serif;overflow:auto;">
    <label ID:><%= exchange.id %></label>
    <b><label Exchange Contents:></b><%= @current_restaurant.restaurant_foods.each {|food| food.food_type} %></label>
</div>
<% end %>

app/views/exchanges/new.html.erb
<h1> A new exchange? Wow. You're the real hero here. </h1>

<h3> Hunger is a major problem in NYC. With your generosity, </h3>
<h3> we can help alleviate it for those throughout our great city. </h3>

<%= form_for @exchange do |f| %>

    <%= f.hidden_field :restaurant_id %>
    <%= hidden_field_tag @current_restaurant.id %>

    <%= f.label :exchange_start %>
    <%= f.datetime_select :exchange_start %>

    <%= f.label :exchange_end %>
    <%= f.datetime_select :exchange_end %>

    <%= f.label :notes %>
    <%= f.text_area :notes %>

    <%= f.submit "Create Exchange!" %>

<% end %>

app/views/exchanges/show.html.erb
<h1><% @exchange%></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SustainabLy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <ul>
        <li><%= link_to 'Restaurants Home', restaurants_path %></li>
        <li><%= link_to 'Organizations Home', organizations_path %></li>
        <li><%= link_to 'New Exchange', new_exchange_path %></li>
        <% if @current_restaurant %>
          <li class='right'>Welcome <%= @current_restaurant.name %></li>
        <% else %>
          <li class='right'><%= link_to 'Sign Up As Restaurant', new_restaurant_path %></li>
        <% end %>
      </ul>
    <%= yield %>
  </body>
</html>

app/views/organizations/edit.html.erb
<h1> Edit <%= @organization.name %> </h1>

<%= form_for @organization do |f|%>

    <%= f.label :name %>
    <%= f.text_field :name %> <%#validate for presence%>
    
    <%= f.label :street_address %>
    <%= f.text_field :street_address %> <%#validate for presence, structure%>

    <%= f.label :city %>
    <%= f.text_field :city %> <%#validate for presence, structure%>

    <%= f.label :state %>
    <%= f.text_field :state %> <%#validate for presence, structure%>

    <%= f.label :zip_code %>
    <%= f.text_field :zip_code%>

    <%= f.label :contact_email %>
    <%= f.text_field :contact_email %> 

    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %> 

    <%= f.submit "Confirm Changes" %>
<% end %>

app/views/organizations/index.html.erb
<h1>Our Valued Organizations</h1>
<% @organizations.all.each do |organization|%>
<br><li><%=link_to organization.name, organization_path(organization.id) %></li></br>
<%end%>

app/views/organizations/new.html.erb
<h1> New Organization Form </h1>
<ul>
<%= form_for @organization do |f|%>

    <%= f.label :name %>
    <%= f.text_field :name %> <%#validate for presence%>
    
    <%= f.label :street_address %>
    <%= f.text_field :street_address %> <%#validate for presence, structure%>

    <%= f.label :city %>
    <%= f.text_field :city %> <%#validate for presence, structure%>

    <%= f.label :state %>
    <%= f.text_field :state %> <%#validate for presence, structure%>

    <%= f.label :zip_code %>
    <%= f.text_field :zip_code%>

    <%= f.label :contact_email %>
    <%= f.text_field :contact_email %> 

    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %> 

    <%= f.submit "Join Sustainab.ly" %>
<% end %>
</ul>

app/views/organizations/show.html.erb
<h1>Welcome to Sustainab.ly, <%=@organization.name%>!</h1>

<h3> Below is the information we have on record for you:</h3>
<ul>
    <li>Street Address: <%= @organization.street_address %></li>
    <li>City:<%= @organization.city %></li>
    <li>State:<%= @organization.state %></li>
    <li>Zip Code:<%= @organization.zip_code %></li>
    <li>Contact Email: <%= @organization.contact_email %></li>
    <li>Phone Number:<%= @organization.phone_number %></li>
</ul>

app/views/restaurant_foods/edit.html.erb
<h1> Heard you wanted to change something up, <%= @current_restaurant.name %>! </h1>

<%= form_for @restaurant_food do |f|%>
    
    <%= f.label :food_type %>
    <%= f.text_field :food_type %> <%#validate for presence, structure%>

    <%= f.label :quantity %>
    <%= f.text_field :quantity %> <%#validate for presence, structure%>

    <%= f.label :use_by %>
    <%= f.datetime_field :use_by %> <%#validate for presence, structure%>

    <%= f.label :notes %>
    <%= f.text_area :notes%>

    <%= f.submit "Confirm Changes" %>

<% end %>

app/views/restaurant_foods/index.html.erb
<h1><%= @current_restaurant.name %>'s Food List </h1>

app/views/restaurant_foods/new.html.erb
<h1> Add Food To Your Restaurant </h1>

<p> Fill out the fields below to add to add a record of excess food to your database.</p><br>
<p> Once added, you'll be able to add it to the Sustainab.ly Marketplace and other Companies will be able to see what you got!</p>

<%= form_for @restaurant_food do |f|%>

    <%= f.label :restaurant_id %>
  <%#validate for presence//add session%>
    
    <%= f.label :food_type %>
    <%= f.text_field :food_type %> <%#validate for presence, structure%>

    <%= f.label :quantity %>
    <%= f.text_field :quantity %> <%#validate for presence, structure%>

    <%= f.label :use_by %>
    <%= f.datetime_field :use_by %> <%#validate for presence, structure%>

    <%= f.label :notes %>
    <%= f.text_field :notes %>

    <%= f.submit "Add Food To Restaurant List" %>
<% end %>

app/views/restaurants/edit.html.erb
<h1> Edit <%= @restaurant.name %> </h1>

<%= form_for @restaurant do |f|%>

    <%= f.label :name %>
    <%= f.text_field :name %> <%#validate for presence%>
    
    <%= f.label :street_address %>
    <%= f.text_field :street_address %> <%#validate for presence, structure%>

    <%= f.label :city %>
    <%= f.text_field :city %> <%#validate for presence, structure%>

    <%= f.label :state %>
    <%= f.text_field :state %> <%#validate for presence, structure%>

    <%= f.label :zip_code %>
    <%= f.text_field :zip_code%>

    <%= f.label :contact_email %>
    <%= f.text_field :contact_email %> 

    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %> 

    <%= f.submit "Confirm Changes" %>
<% end %>

app/views/restaurants/new.html.erb
<h1> New Restaurant Form </h1>

<%= form_for @restaurant do |f|%>

    <%= f.label :name %>
    <%= f.text_field :name %> <%#validate for presence%>

    <%= f.label :password_digest %>
    <%= f.password_field :password_digest %>
    
    <%= f.label :street_address %>
    <%= f.text_field :street_address %> <%#validate for presence, structure%>

    <%= f.label :city %>
    <%= f.text_field :city %> <%#validate for presence, structure%>

    <%= f.label :state %>
    <%= f.text_field :state %> <%#validate for presence, structure%>

    <%= f.label :zip_code %>
    <%= f.text_field :zip_code%>

    <%= f.label :contact_email %>
    <%= f.text_field :contact_email %> 

    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %> 

    <%= f.submit "Join Sustainab.ly" %>
<% end %>

app/views/restaurants/show.html.erb
<h1>Hey there, <%= @restaurant.name %>!</h1>

<h3> Below is the information on record for you:</h3>
<ul>
    <li>Street Address: <%= @restaurant.street_address %></li>
    <li>City:<%= @restaurant.city %></li>
    <li>State:<%= @restaurant.state %></li>
    <li>Zip Code:<%= @restaurant.zip_code %></li>
    <li>Contact Email: <%= @restaurant.contact_email %></li>
    <li>Phone Number:<%= @restaurant.phone_number %></li>
</ul>
<%= button_to "Update Restaurant", edit_restaurant_path(@restaurant), method: :get %>

<h3> Our Food List </h3>

<ul>
    <% @current_restaurant.restaurant_foods.each do |food| %>
        <li> Type: <%= food.food_type %></li><br>
        <li> Quantity: <%= food.quantity %></li><br>
        <li> Use By: <%= food.use_by %></li><br>
        <li> Notes: <%= food.notes %></li><br>
        <%= button_to "Edit Food", edit_restaurant_food_path(food), method: :get %>
    <% end %>
</ul>

<%= button_to "Add Food To Your List", new_restaurant_food_path, method: :get %> <%= button_to "Create Exchange", new_exchange_path, method: :get %>